---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/samratashok/nishang", location: "/opt/nishang" }
    - {repo: "https://github.com/empty-jack/YAWR", location: "/opt/YAWR"}
    - {repo: "https://github.com/jtesta/ssh-audit", location: "/opt/ssh-audit"}
    # - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists" } # This repo is already installed by default on Kali Linux
    # - {repo: "https://github.com/RedSiege/EyeWitness", location: "/opt/EyeWitness"} # installed via apt
    # - {repo: "https://github.com/secdev/scapy/", location: "/opt/scapy"} # installed via apt
  become: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "python3 {{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop:
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", location: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", location: "/opt/chisel" }
    - { repo: "ginuerzh/gost",  regex: "gost-linux-amd64-", location: "/opt/gost" }
    - { repo: "ginuerzh/gost",  regex: "gost-windows-amd64-", location: "/opt/gost" }
    #- { repo: "jpillora/chisel",  regex: "_darwin_amd64", location: "/opt/chisel", filename: "chisel_osx" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", location: "/opt/PEASS" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", location: "/opt/PEASS" }
    - { repo: "WithSecureLabs/chainsaw",  regex: "chainsaw_all_", location: "/opt/" }
    #- { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", location: "/opt/" }
  async: 45
  poll: 0
  become: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined
  become: true
